"""add course_code to Course

Revision ID: 4dbf467f1eb4
Revises: 44bc4606a9ce
Create Date: 2025-11-17 21:46:28.260906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4dbf467f1eb4'
down_revision: Union[str, Sequence[str], None] = '44bc4606a9ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('file_url', sa.String(length=255), nullable=False))
    op.drop_column('contents', 'file_path')
    op.add_column('courses', sa.Column('course_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'course_code')
    op.add_column('contents', sa.Column('file_path', mysql.VARCHAR(length=255), nullable=False))
    op.drop_column('contents', 'file_url')
    # ### end Alembic commands ###
